# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditCoffeeForm(object):
    def setupUi(self, EditCoffeeForm):
        EditCoffeeForm.setObjectName("EditCoffeeForm")
        EditCoffeeForm.setWindowModality(QtCore.Qt.ApplicationModal)
        EditCoffeeForm.resize(565, 345)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EditCoffeeForm.sizePolicy().hasHeightForWidth())
        EditCoffeeForm.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        EditCoffeeForm.setFont(font)
        EditCoffeeForm.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        EditCoffeeForm.setSizeGripEnabled(True)
        EditCoffeeForm.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(EditCoffeeForm)
        self.gridLayout.setObjectName("gridLayout")
        self.type_label = QtWidgets.QLabel(EditCoffeeForm)
        self.type_label.setObjectName("type_label")
        self.gridLayout.addWidget(self.type_label, 2, 0, 1, 1)
        self.description_label = QtWidgets.QLabel(EditCoffeeForm)
        self.description_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.description_label.setObjectName("description_label")
        self.gridLayout.addWidget(self.description_label, 5, 0, 1, 1)
        self.packing_sb = QtWidgets.QSpinBox(EditCoffeeForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.packing_sb.sizePolicy().hasHeightForWidth())
        self.packing_sb.setSizePolicy(sizePolicy)
        self.packing_sb.setMinimumSize(QtCore.QSize(80, 0))
        self.packing_sb.setMaximum(100000)
        self.packing_sb.setObjectName("packing_sb")
        self.gridLayout.addWidget(self.packing_sb, 4, 1, 1, 1)
        self.price_dsb = QtWidgets.QDoubleSpinBox(EditCoffeeForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.price_dsb.sizePolicy().hasHeightForWidth())
        self.price_dsb.setSizePolicy(sizePolicy)
        self.price_dsb.setMinimumSize(QtCore.QSize(80, 0))
        self.price_dsb.setMaximum(1000000.0)
        self.price_dsb.setObjectName("price_dsb")
        self.gridLayout.addWidget(self.price_dsb, 3, 1, 1, 1)
        self.price_label = QtWidgets.QLabel(EditCoffeeForm)
        self.price_label.setObjectName("price_label")
        self.gridLayout.addWidget(self.price_label, 3, 0, 1, 1)
        self.roast_type_label = QtWidgets.QLabel(EditCoffeeForm)
        self.roast_type_label.setObjectName("roast_type_label")
        self.gridLayout.addWidget(self.roast_type_label, 1, 0, 1, 1)
        self.packing_label = QtWidgets.QLabel(EditCoffeeForm)
        self.packing_label.setObjectName("packing_label")
        self.gridLayout.addWidget(self.packing_label, 4, 0, 1, 1)
        self.name_label = QtWidgets.QLabel(EditCoffeeForm)
        self.name_label.setObjectName("name_label")
        self.gridLayout.addWidget(self.name_label, 0, 0, 1, 1)
        self.type_cb = QtWidgets.QComboBox(EditCoffeeForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.type_cb.sizePolicy().hasHeightForWidth())
        self.type_cb.setSizePolicy(sizePolicy)
        self.type_cb.setMinimumSize(QtCore.QSize(200, 0))
        self.type_cb.setObjectName("type_cb")
        self.gridLayout.addWidget(self.type_cb, 2, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(EditCoffeeForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 7, 1, 1, 1)
        self.name_edit = QtWidgets.QLineEdit(EditCoffeeForm)
        self.name_edit.setObjectName("name_edit")
        self.gridLayout.addWidget(self.name_edit, 0, 1, 1, 1)
        self.roast_type_cb = QtWidgets.QComboBox(EditCoffeeForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roast_type_cb.sizePolicy().hasHeightForWidth())
        self.roast_type_cb.setSizePolicy(sizePolicy)
        self.roast_type_cb.setMinimumSize(QtCore.QSize(200, 0))
        self.roast_type_cb.setObjectName("roast_type_cb")
        self.gridLayout.addWidget(self.roast_type_cb, 1, 1, 1, 1)
        self.description_edit = QtWidgets.QPlainTextEdit(EditCoffeeForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.description_edit.sizePolicy().hasHeightForWidth())
        self.description_edit.setSizePolicy(sizePolicy)
        self.description_edit.setTabChangesFocus(True)
        self.description_edit.setObjectName("description_edit")
        self.gridLayout.addWidget(self.description_edit, 5, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 6, 1, 1, 1)

        self.retranslateUi(EditCoffeeForm)
        self.buttonBox.accepted.connect(EditCoffeeForm.accept)
        self.buttonBox.rejected.connect(EditCoffeeForm.reject)
        QtCore.QMetaObject.connectSlotsByName(EditCoffeeForm)
        EditCoffeeForm.setTabOrder(self.name_edit, self.roast_type_cb)
        EditCoffeeForm.setTabOrder(self.roast_type_cb, self.type_cb)
        EditCoffeeForm.setTabOrder(self.type_cb, self.price_dsb)
        EditCoffeeForm.setTabOrder(self.price_dsb, self.packing_sb)
        EditCoffeeForm.setTabOrder(self.packing_sb, self.description_edit)

    def retranslateUi(self, EditCoffeeForm):
        _translate = QtCore.QCoreApplication.translate
        self.type_label.setText(_translate("EditCoffeeForm", "Тип"))
        self.description_label.setText(_translate("EditCoffeeForm", "Описание"))
        self.price_label.setText(_translate("EditCoffeeForm", "Цена, руб."))
        self.roast_type_label.setText(_translate("EditCoffeeForm", "Обжарка"))
        self.packing_label.setText(_translate("EditCoffeeForm", "Вес, гр"))
        self.name_label.setText(_translate("EditCoffeeForm", "Название"))
